/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package amka.kt

import kotlin.test.Test
import kotlin.test.assertTrue
import kotlin.test.assertFalse

class AmkaTest {
    @Test fun it_validates_valid_amka() {
        val (isValid, error) = Amka().isValid("09095986684")
        assertTrue(isValid, "isValid should return 'true'")
    }

    @Test fun it_fails_when_not_a_number() {
        val (isValid, error) = Amka().isValid("asvs")
        assertFalse(isValid, "isValid should return 'true'")
    }

    @Test fun it_fails_when_short_number() {
        val (isValid, error) = Amka().isValid("09095986")
        assertFalse(isValid, "isValid should return 'true'")
    }

    @Test fun it_fails_when_long_number() {
        val (isValid, error) = Amka().isValid("090959866845")
        assertFalse(isValid, "isValid should return 'true'")
    }

    @Test fun it_fails_when_not_a_valid_date() {
        val (isValid, error) = Amka().isValid("39095986681")
        assertFalse(isValid, "isValid should return 'true'")
    }

    @Test fun it_fails_with_bad_checkdigit() {
        val (isValid, error) = Amka().isValid("09095986680")
        assertFalse(isValid, "isValid should return 'true'")
    }
}
